# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: ultra_light_wizard 0.1.2 ruby lib

Gem::Specification.new do |s|
  s.name = "ultra_light_wizard"
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Andy Maleh"]
  s.date = "2017-02-22"
  s.description = "Ultra light & maintainble wizards in Rails that honor REST, MVC, and OO with minimal writing of code involved and maximum flexibility"
  s.email = "andy.am@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".ruby-gemset",
    ".ruby-version",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/generators/templates/app/controllers/wizard_steps_controller.rb.erb",
    "lib/generators/templates/app/helpers/wizard_steps_helper.rb.erb",
    "lib/generators/templates/app/models/wizard_step_model.rb.erb",
    "lib/generators/templates/app/views/wizard_step_navigation_view.html.erb",
    "lib/generators/templates/app/views/wizard_step_view.html.erb",
    "lib/generators/ultra_light_wizard/scaffold_generator.rb",
    "lib/ultra_light_wizard.rb",
    "ruby187.Gemfile",
    "spec/spec_helper.rb",
    "spec/ultra_light_wizard/ultra_light_wizard_spec.rb",
    "ultra_light_wizard.gemspec",
    "ultra_light_wizard.jpg"
  ]
  s.homepage = "http://github.com/AndyObtiva/ultra_light_wizard"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.5.1"
  s.summary = "Ultra Light & Maintainable Wizards In Rails"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.8"])
    else
      s.add_dependency(%q<jeweler>, ["~> 1.8.8"])
    end
  else
    s.add_dependency(%q<jeweler>, ["~> 1.8.8"])
  end
end

