# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: ultra_light_wizard 0.0.1 ruby lib

Gem::Specification.new do |s|
  s.name = "ultra_light_wizard"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Andy Maleh"]
  s.date = "2015-03-17"
  s.description = "Ultra light & maintainble wizards in Rails that honor REST, MVC, and OO with minimal writing of code involved and maximum flexibility"
  s.email = "andy.am@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md",
    "README.rdoc"
  ]
  s.files = [
    ".ruby-gemset",
    ".ruby-version",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "README.rdoc",
    "Rakefile",
    "demo/project_portfolio/.gitignore",
    "demo/project_portfolio/Gemfile",
    "demo/project_portfolio/Gemfile.lock",
    "demo/project_portfolio/README.rdoc",
    "demo/project_portfolio/Rakefile",
    "demo/project_portfolio/app/assets/images/.keep",
    "demo/project_portfolio/app/assets/javascripts/application.js",
    "demo/project_portfolio/app/assets/stylesheets/application.css",
    "demo/project_portfolio/app/controllers/application_controller.rb",
    "demo/project_portfolio/app/controllers/concerns/.keep",
    "demo/project_portfolio/app/helpers/application_helper.rb",
    "demo/project_portfolio/app/mailers/.keep",
    "demo/project_portfolio/app/models/.keep",
    "demo/project_portfolio/app/models/concerns/.keep",
    "demo/project_portfolio/app/views/layouts/application.html.erb",
    "demo/project_portfolio/bin/bundle",
    "demo/project_portfolio/bin/rails",
    "demo/project_portfolio/bin/rake",
    "demo/project_portfolio/bin/spring",
    "demo/project_portfolio/config.ru",
    "demo/project_portfolio/config/application.rb",
    "demo/project_portfolio/config/boot.rb",
    "demo/project_portfolio/config/cucumber.yml",
    "demo/project_portfolio/config/database.yml",
    "demo/project_portfolio/config/environment.rb",
    "demo/project_portfolio/config/environments/development.rb",
    "demo/project_portfolio/config/environments/production.rb",
    "demo/project_portfolio/config/environments/test.rb",
    "demo/project_portfolio/config/initializers/assets.rb",
    "demo/project_portfolio/config/initializers/backtrace_silencers.rb",
    "demo/project_portfolio/config/initializers/cookies_serializer.rb",
    "demo/project_portfolio/config/initializers/filter_parameter_logging.rb",
    "demo/project_portfolio/config/initializers/inflections.rb",
    "demo/project_portfolio/config/initializers/mime_types.rb",
    "demo/project_portfolio/config/initializers/session_store.rb",
    "demo/project_portfolio/config/initializers/wrap_parameters.rb",
    "demo/project_portfolio/config/locales/en.yml",
    "demo/project_portfolio/config/routes.rb",
    "demo/project_portfolio/config/secrets.yml",
    "demo/project_portfolio/db/schema.rb",
    "demo/project_portfolio/db/seeds.rb",
    "demo/project_portfolio/features/step_definitions/.gitkeep",
    "demo/project_portfolio/features/support/env.rb",
    "demo/project_portfolio/lib/assets/.keep",
    "demo/project_portfolio/lib/tasks/.keep",
    "demo/project_portfolio/lib/tasks/cucumber.rake",
    "demo/project_portfolio/log/.keep",
    "demo/project_portfolio/public/404.html",
    "demo/project_portfolio/public/422.html",
    "demo/project_portfolio/public/500.html",
    "demo/project_portfolio/public/favicon.ico",
    "demo/project_portfolio/public/robots.txt",
    "demo/project_portfolio/script/cucumber",
    "demo/project_portfolio/spec/rails_helper.rb",
    "demo/project_portfolio/spec/spec_helper.rb",
    "demo/project_portfolio/test/controllers/.keep",
    "demo/project_portfolio/test/fixtures/.keep",
    "demo/project_portfolio/test/helpers/.keep",
    "demo/project_portfolio/test/integration/.keep",
    "demo/project_portfolio/test/mailers/.keep",
    "demo/project_portfolio/test/models/.keep",
    "demo/project_portfolio/test/test_helper.rb",
    "demo/project_portfolio/vendor/assets/javascripts/.keep",
    "demo/project_portfolio/vendor/assets/stylesheets/.keep",
    "lib/generators/wizard_generator.rb",
    "lib/templates/app/controllers/model_parts_controller.rb",
    "lib/templates/app/controllers/models_controller.rb",
    "lib/ultra_light_wizard.rb",
    "ruby187.Gemfile",
    "spec/spec_helper.rb",
    "spec/ultra_light_wizard/ultra_light_wizard_spec.rb"
  ]
  s.homepage = "http://github.com/AndyObtiva/ultra_light_wizard"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.6"
  s.summary = "Ultra Light & Maintainable Wizards In Rails"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.8"])
      s.add_development_dependency(%q<rspec>, ["~> 2.14.1"])
      s.add_development_dependency(%q<cucumber>, ["~> 1.3.19"])
      s.add_development_dependency(%q<coveralls>, ["~> 0.7.0"])
      s.add_development_dependency(%q<rails>, ["~> 4.1.9"])
    else
      s.add_dependency(%q<jeweler>, ["~> 1.8.8"])
      s.add_dependency(%q<rspec>, ["~> 2.14.1"])
      s.add_dependency(%q<cucumber>, ["~> 1.3.19"])
      s.add_dependency(%q<coveralls>, ["~> 0.7.0"])
      s.add_dependency(%q<rails>, ["~> 4.1.9"])
    end
  else
    s.add_dependency(%q<jeweler>, ["~> 1.8.8"])
    s.add_dependency(%q<rspec>, ["~> 2.14.1"])
    s.add_dependency(%q<cucumber>, ["~> 1.3.19"])
    s.add_dependency(%q<coveralls>, ["~> 0.7.0"])
    s.add_dependency(%q<rails>, ["~> 4.1.9"])
  end
end

